### PR TITLE
Implementing details management feature on forms in "Monthly Report" page

### PR DESCRIPTION
**Pull request by dondippino**
bug_reporthub_29_07_2020
**The Problem**

- The details section of the form, on the monthly report page (https://reporthub.org/desk/#/cluster/projects/report/<project_id>/<report_id>) does not display the input values (if any) while also it disappears at the submission of activities. 

- This presents a great challenge for the users, as they think that their entries are not saved.

- Rendering all the details per location at once, might cause a huge drag in performance of the page (for large numbers of locations).

**The Proposal**

- Display the current state of 'details' in activities that have details, by rendering the details as hyperlinked strings 

- Users can now click these links, to open the details section of the form. At this point angular will fetch the details template and render the form for that particular card

### CODE REVIEW

**Comment by drfaustusfade** [comment]
there is a bug that existing details are overwritten, please check
https://github.com/pfitzpaddy/ngm-reportHub/pull/475

**Comment by dondippino** [comment]
Please can you explain this bug further, A gif could go a long way

**Comment by drfaustusfade** [comment]
that's quite an advanced solution with directives and compilations, what do you think to have simple open/close functionality the same as entire activity form with ng-if? That is to have details formatted string by default closed and on a click that would open form?
H2VPCnY3T6

**Comment by dondippino** [comment]
You are right, a simple solution would have sufficed. But I was thinking that the rendering time of the page will be affected when we have hundreds of locations with details. So I had to use that approach to render only details that are of interest per time

**Comment by pfitzpaddy** [comment]
The existing "lazy-loading" of the locations / beneficiaries cards that we have in place might help avoid any page load times issue with such the `ng-if` approach?

**Comment by drfaustusfade** [comment]
that should help as ngIf works with the DOM, so that would render only on true condition

**Comment by dondippino** [comment]
Let us use the ng-if approach, since it is simpler.

**Pull request closed without merging**
