### PR TITLE
Feature cp prev report

### PR DESCRIPTION
**Pull request by drfaustusfade**
copies rows from the previos report,
adds to existing, optionally can overwrite

### CODE REVIEW

**Comment by pfitzpaddy** [comment]
Around what timeframe would it be possible to see this in the Monthly Report? Also, for monthly report, could we the following functionality 1) Copy entire month, 2) Copy individual locations (this is because currently in Ethiopia there is different reporters per location)? Thoughts..?

**Comment by drfaustusfade** [comment]
not much time, just adjust to monthly report, I put it on agenda on week after, as next week, we have 3 days of training, as per reporter we can filter and add based on a reporter.
so focal point can copy entire month, and individual location based on user assigned.

**Comment by pfitzpaddy** [comment]
Ok thats more then perfect - thanks @drfaustusfade!

**Comment by pfitzpaddy** [comment]
Merged on DEV and PROD

**Pull request merged**
