### PR TITLE
feature: project partners project/locations multiple selections

### PR DESCRIPTION
**Pull request by fakhrihawari**

### CODE REVIEW

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD

**Comment by pfitzpaddy** [comment]
There was an error when adding new locations (when location.length is zero). I went back to previous commit

**Comment by pfitzpaddy** [comment]
This line is causing the error https://github.com/pfitzpaddy/ngm-reportHub/pull/180/files#diff-a6caa72a087852968100595b17b711e6R75.
Also, `implementing_partners_array` is not in the ngm-reportEngine models, `implementing_partners` is now an array in the models (not a string) so this can be used directly.

**Comment by fakhrihawari** [comment]
thank you ,  i will fix it

**Comment by fakhrihawari** [comment]
pull request
https://github.com/pfitzpaddy/ngm-reportHub/pull/181

**Comment by fakhrihawari** [comment]
Fix pull request 
https://github.com/pfitzpaddy/ngm-reportHub/pull/182

**Pull request merged**
