### PR TITLE
Update promo page metrics text.

### PR DESCRIPTION
**Pull request by drfaustusfade**
Results in:
chrome_2017-10-23_13-43-11

### CODE REVIEW

**Comment by pfitzpaddy** [comment]
Looks good, some updates. Please go with;

> ReportHub is still less then a year old but has already contributed to the humanitarian response efforts in Afghanistan. Initially implemented by the Health Cluster, ReportHub has since been expanded to cover the all Clusters and Working Groups as the HRP reporting platform for Afghanistan. Once partners submit a report, Cluster indicators are available in real-time from the dashboard and directly link with OCHAs HPC.tools for HRP reporting. Currently, ReportHub has 403 users reporting on 3081 Locations for which 1521 beneficiary reports have been submitted.

**Comment by drfaustusfade** [comment]
Thanks! Updated:
chrome_2017-10-23_14-14-04

**Comment by drfaustusfade** [comment]
Additional proposed changes by communication officer:
_Since its launch in April 2017, ReportHub has significantly_ contributed to the humanitarian response efforts in Afghanistan. Initially implemented by the Health Cluster, ReportHub has since expanded to cover all Humanitarian Clusters and Working Groups as the official HRP reporting platform for Afghanistan. Once partners submit a report, cluster indicators are available in real-time, from the dashboard, and directly linked with UNOCHA´s HPC tools for HRP reporting.

**Comment by pfitzpaddy** [comment]
Not sure what to do with here exactly with this. ReportHub was endorsed by the Health Minister as the Health Cluster reporting tool in May, 2016 (so offical launch was more like May 2016). Then in Feb 2017 the ICCT decided to adopt the tool for all clusters, rolled out in April 2017.

**Comment by AhmedBayomie** [comment]
so we have two dates
 May 2016 (Health Cluster )
April 2017 role out for all clusters
 I would go with April 2017 cause it gives a good image on quick achievement and successful role out

**Comment by pfitzpaddy** [comment]
Yea its a tough one, im not convinced yet since Health is our most likely avenue for the tool to pickup support from a global cluster, so a longer implementation time is probably good. We could make comments around the quick adjustment and roll out to the remaining sectors in April 2017

**Comment by AhmedBayomie** [comment]
i got your point and we can have both i think ( by adding that it started in HC 2016 )
"Since its launch in April 2017, ReportHub has significantly contributed to the humanitarian response efforts in Afghanistan. Initially implemented by the Health Cluster in 2016, ReportHub has since expanded to cover all Humanitarian Clusters and Working Groups as the official HRP reporting platform for Afghanistan. Once partners submit a report, cluster indicators are available in real-time, from the dashboard, and directly linked with UNOCHA´s HPC tools for HRP reporting."

let us conclude quickly on this

**Comment by pfitzpaddy** [comment]
Thanks Ahmed its good, lets go with a couple of minor updates;

> Since its launch in April 2017, ReportHub has significantly contributed to the humanitarian response efforts in Afghanistan by providing decision support in real-time. Initially implemented by the Afghanistan Health Cluster in 2016, ReportHub has since been expanded at the request of the ICCT to cover the reporting needs of all Afghanistan Humanitarian Clusters and Working Groups. In doing so, ReportHub has become the official HRP reporting platform for Afghanistan and is now being expanded into the Horn of Africa. Once partners submit a report, cluster indicators are available in real-time for analysis via RESTful APIs, from the dashboard for decision support and with direct links to UNOCHA's HPC tools for HRP reporting.

**Comment by AhmedBayomie** [comment]
Ok that looks good
go with it

**Pull request merged**
