### PR TITLE
update-fsac

### PR DESCRIPTION
**Pull request by fakhrihawari**

### CODE REVIEW

**Comment by pfitzpaddy** [comment]
Nice work @fakhrihawari. I have made the following small updates;
- Placed all new HTML files in AF sub folder
- Updated upload outline color from blue to teal
- Included back to project summary button
- Updated title

Questions;
- I didnt see assessment_fsac.html used, is that ok?
- Should the following uploads be visible from my FSAC account? I think maybe its possible to see all uploads for any project across everyones account?
reporthub-fsac-01

**Comment by fakhrihawari** [comment]
- assessment_fsac.html that's just my mock-up, because at that time I have no idea what should put it in the assessment 
- No, that just HTML not working yet. And when I make this upload is just to post any kind of file that relate to the project. I think we can make it so we can see all upload but in a different page or in this page

**Comment by pfitzpaddy** [comment]
I think the ability to have Grid and List views is secondary priority. First is the complete upload. We can store it on ReportHub server for now to get it working but we will need to figure out a place for the documents / storage.

**Comment by drfaustusfade** [comment]
Hey there, 
- the above is just an interface preview for FSAC workshop, not working functionality, maybe it should not be in production for use, could be ng-hide on the card for a while
- gdrive interface is a model for "reporthubdrive", but first yes we implement a simple list view
- storage: first our server, then on our s3 or gdrive (more ready in functionality, there are any thumbnail documents previews, not expensive for space, and more user friendly to configure for people who will install rh on their servers )

**Pull request merged**
