### PR TITLE
feature: add minimize/maximize button and search for beneficiaries

### PR DESCRIPTION
**Pull request by fakhrihawari**
3yXBE5mWWt

### CODE REVIEW

**Comment by fakhrihawari** [comment]
For monthly report

**Comment by pfitzpaddy** [comment]
1. When report is submitted or when project is complete, unable to maximise beneficiary card
Screen Shot 2019-06-19 at 4 09 25 pm

2. Update Card Title (for both targets and monthly beneficiaries)
- List activity_type, description, details on the top line
- Add only Beneficiary type on the second line (and make text color the same as the beneficiary total for that card `#565656`
- Add padding between each row of beneficiaries when minimized only

**Comment by fakhrihawari** [comment]
Add unable and Update Card Title
title-minim-fix
monthly beneficiaries

t-title-fix
target beneficiaries

**Comment by fakhrihawari** [comment]
i will fix it ,and then make pull request again

**Comment by drfaustusfade** [comment]
> 1. When report is submitted or when project is complete, unable to maximise beneficiary card
> 
> Screen Shot 2019-06-19 at 4 09 25 pm
> 
> 1. Update Card Title (for both targets and monthly beneficiaries)
> 
> * List activity_type, description, details on the top line
> * Add only Beneficiary type on the second line (and make text color the same as the beneficiary total for that card `#565656`
> * Add padding between each row of beneficiaries when minimized only

looks like report buttons disabled on screenshot because of user rights (edit report is disabled), as if user not allowed to edit it will disable fieldset if all users should be able to maximize if any user should be able to expand fake div button could be used

**Comment by fakhrihawari** [comment]
New link pull request:
https://github.com/pfitzpaddy/ngm-reportHub/pull/236

**Pull request closed without merging**
