### PR TITLE
fix-bug input(detail page) on materialize 1x

### PR DESCRIPTION
**Pull request by fakhrihawari**

### CODE REVIEW

**Comment by pfitzpaddy** [comment]
Following small cosmetic issues;
1. Inputs have issue when error. The labels go small and are not displayed red, some inputs should be displayed in red (inputs with asterix)
rh_css_error

**Comment by fakhrihawari** [comment]
Screen Shot 2020-01-17 at 17 47 49

**Comment by pfitzpaddy** [comment]
Ok good point. Can you make Red error text in **Bold** - also, I see that in PROD currently, Donor label is also not red. Please also check monthly report. All error labels are not displaying in red.

**Comment by fakhrihawari** [comment]
Screen Shot 2020-01-17 at 18 08 44

monthly report label is red like that

**Comment by pfitzpaddy** [comment]
Great, must be my local then.

**Comment by pfitzpaddy** [comment]
Updated on DEV and PROD

**Pull request merged**
